name: grav
type: php:7.0
disk: 2048
web:
  locations:
    '/':
      root: 'public'
      passthru: '/index.php'
      allow: false
      rules:
        '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
          allow: true
        '^/robots\.txt$':
          allow: true

mounts:
  "public/user/accounts": "shared:files/accounts"
  "public/user/data": "shared:files/data"
  "public/user/pages": "shared:files/pages"
  "public/user/config": "shared:files/config"
  "public/assets": "shared:files/assets"
  "public/backup": "shared:files/backup"
  "public/cache/doctrine": "shared:files/cache_doctrine"
  "public/cache/compiled": "shared:files/cache_compiled"
  "public/images": "shared:files/images"
  "public/logs": "shared:files/logs"
  "pub/tmp": "shared:files/tmp"

hooks:
  build: |
    cd public && composer install
    cd -
    cd public/user/themes && wget https://github.com/getgrav/grav-theme-antimatter/archive/2.1.0.tar.gz
    tar xzvf 2.1.0.tar.gz
    mv grav-theme-antimatter-2.1.0 antimatter