name: grav
type: php:7.0
disk: 2048
web:
  locations:
    '/':
      root: 'public'
      passthru: '/index.php'
      allow: false
      rules:
        '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
          allow: true
        '^/robots\.txt$':
          allow: true

mounts:
  "public/user/accounts": "shared:files/accounts"
  "public/user/data": "shared:files/data"
  "public/user/pages": "shared:files/pages"

hooks:
  build: |
    cd public && composer install